# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 \
  -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 \
  -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 \
  -Dhttp.nonProxyHosts=localhost|127.0.0.1 \
  -Dhttps.nonProxyHosts=localhost|127.0.0.1
org.gradle.parallel=true
org.gradle.caching=true
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1

# Java proxy settings
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home

# Android settings
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Non-transitive R classes
android.nonTransitiveRClass=true
